[network]
bind_address = "127.0.0.1"
external_address = "127.0.0.1"
bind_port = 5555
allow_any_host = true

[auth]
keys = ["refinery-dev"]

[registry]
include_coral_home_agents = false
include_debug_agents = false
export_debug_agents = false
watch_local_agents = true
local_agent_rescan_timer = "10s"
local_agents = ["coral/agents/*"]
